[package]
name = "tokio-tls"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-tls"
homepage = "https://github.com/tokio-rs/tokio-tls"
documentation = "https://docs.rs/tokio-tls"
description = """
An implementation of TLS/SSL streams for Tokio giving an implementation of TLS
for nonblocking I/O streams.
"""

[dependencies]
futures = "0.1.4"
tokio-core = "0.1.1"
native-tls = "0.1"

[dev-dependencies]
env_logger = { version = "0.3", default-features = false }
cfg-if = "0.1"

[target.'cfg(all(not(target_os = "macos"), not(windows)))'.dev-dependencies]
openssl = "0.9"

[target.'cfg(target_os = "macos")'.dev-dependencies]
security-framework = "0.1"

[target.'cfg(windows)'.dev-dependencies]
advapi32-sys = "0.2"
crypt32-sys = "0.2"
kernel32-sys = "0.2"
schannel = "0.1"
winapi = "0.2"

[replace.'native-tls:0.1.0']
git = 'https://github.com/sfackler/rust-native-tls'
